import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: side-effect import of CSS without declaration; consider adding a global .d.ts with "declare module '*.css';"
import "./globals.css";

import { NavbarWrapper } from "@/components/NavbarWrapper";
import Footer from "@/components/Footer";
import StoreProvider from "@/providers/StoreProvider";
import { FooterWrapper } from "@/components/FooterWrapper";
import { ToastProvider } from "@/components/ToastProvider";
import Script from "next/script"; // ✅ ADD THIS
import SocketProvider from "@/providers/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dsport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* ✅ Razorpay Script — GLOBAL */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />

        <StoreProvider>
          <SocketProvider>
          <NavbarWrapper />
          <ToastProvider />
          {children}
          <FooterWrapper />
          </SocketProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
